### ISSUE TITLE
Reminders for set days

### ISSUE THREAD

**Issue by Linschlager** [pcg79/Reminders-Addon#33]
It might be great to be able to schedule reminders for set days.
E.g.: Remind me to sign up for the next raid every sunday or remind me to open the mythic crate every tuesday/wednesday. Just things that are weekly but need to be done on a set day.

Maybe just extend the weekly functionality to be able to be more specific but still work like the weekly reminders.

**Comment by pcg79** [comment]
Could definitely do that!

**Comment by pcg79** [comment]
(Got auto closed by Github.  I'll close it once we're happy it's implemented).

Ok, I just pushed out v8.0.8.beta1 with this change.  I haven't had a chance to test it much but my debug logging leads me to believe it's in good shape.  It should handle existing weekly reminders by setting them to Tuesday (the previous behavior).  New ones should get a "week day" drop down if you choose an interval of "Weekly".

If you get a chance to try out the beta and let me know if it's ok, I'd appreciate it. If not, I'll give it a few days to test locally and then make it a proper release.

**Comment by pcg79** [comment]
This has been released as 8.0.8.  Let me know if you run into any issues with it.
